### ISSUE TITLE
Cannot make it parallel

### ISSUE THREAD

**Issue by DNXie** [yoheikikuta/senet-keras#2]
I create my model like this:  
`model = SEResNeXt(size=256, num_classes=4).model`  
When I try to run the model on several GPUs by    
`parallel_model = multi_gpu_model(model, gpus=nb_gpu)`
I got this error:  
`Concatenate layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, None, None, 32), (None, 128, 128, 64), (None, None, None, 32)]`

`python = 3.4.3`  
`keras = 2.0.9`

**Comment by DNXie** [comment]
@yoheikikuta

**Comment by yoheikikuta** [comment]
@DNXie 

Sorry for the late reply.
To be honest, I don't know the reason because I didn't try multi-gpu.
Since I don't use any special layer in the model, I hope it works.
Two questions:
- can you run training in the case of single gpu?
- did you check `size=96` case? (I don't remember well, but input size can be important.)

**Comment by DNXie** [comment]
@yoheikikuta 
I can't run the model on a single gpu because my image size is 256 which is to big for a single gpu.  When I try to run it on a single gpu, it gives me `ResourceExhaustedError`.     
When I try `size=96`, I got a similar error:    
 `ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, None, None, 32), (None, 48, 48, 64), (None, None, None, 32)]`

**Comment by yoheikikuta** [comment]
@DNXie 
Thanks for checking.
hmm, I cannot identify the cause; I'm sorry I couldn't be of any help :bowing_man: 
If I have a chance, I'll check the multi-gpu case.
